### PR TITLE
Feature/input save functionality

### PR DESCRIPTION
**Pull request by Echory**
Thank you for pushing your code!
What (if any) features are you implementing?
- We implemented a disableButton function.
What (if anything) did you refactor?
- We fixed disableButton styling and cleaned up unnecessary html code. 
Were there any issues that arose?
- na
Is there anything that you need from your teammate?
- Please review edits 
Any other comments, questions, or concerns?

### CODE REVIEW

**Comment by Jorgan612** [comment]
Great job refactoring, make time to revisit the CSS and continue tweaking to match comp.

**Comment by raz-joan** [comment]
This looks good. Nice work on the refactoring of the files!

The button is working! We need to keep taking breaks when we're stuck - that was so helpful. If we have time, let's try to figure out how to enable the button before needing to exit the input fields.

**Review by Jorgan612 — APPROVED** [review]
good to move on to iteration 3

**Review by raz-joan — APPROVED** [review]
Please see my other comment.

**Pull request merged**
